image:
  file: .gitpod.Dockerfile
checkoutLocation: chromium/src/
ports:
- port: 6080
tasks:
- init: >
    mkdir chromium && cd chromium &&
    fetch --nohooks chromium &&
    cd src &&
    gclient runhooks &&
    gn gen out/Default
